# Generated by Django 4.1.3 on 2023-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationform',
            name='statues',
            field=models.CharField(default='pending', max_length=40),
        ),
    ]
